[package]
name = "gtranslate"
version = "0.1.1"
authors = ["sabitmaulana <sabitmaulanaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'  # Optimize for size
lto = true # link-time optimization
codegen-units = 1 # reduce parallel codegen
panic = 'abort' # abort on panic
strip = true

[dependencies]
curl = { version = "0.4.44", default-features = false, features = ["rustls"] }
serde_json = "1.0"
