name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Cache
      uses: actions/cache@v3
      with:
        path: build/*
        key:  build-v1-${{ github.sha }}
        restore-keys: build-v1-
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-musl

    - name: Install gcc for musl aarch64
      run: |
        cd /tmp && curl -LO 'http://musl.cc/aarch64-linux-musl-cross.tgz'
        tar -xvf aarch64-linux-musl-cross.tgz && cd aarch64-linux-musl-cross
        rm -rf share/man/man7 share/locale/ share/gcc-*/ usr
        ln -sfT ../lib/libc.so aarch64-linux-musl/lib/ld-musl-aarch64.so.1
        sudo cp -r "./" /usr/

    - name: Build project for x86_64
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Build project for aarch64
      run: |
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=$(which aarch64-linux-musl-gcc)
        cargo build --release --target=aarch64-unknown-linux-musl

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Binary for x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/x86_64-unknown-linux-gnu/release/gtranslate
        asset_name: gtranslate-x86_64-unknown-linux-gnu
        asset_content_type: application/octet-stream

    - name: Upload Binary for aarch64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/aarch64-unknown-linux-musl/release/gtranslate
        asset_name: gtranslate-aarch64-unknown-linux-musl
        asset_content_type: application/octet-stream
